name: practice-ci-cd
on:
    push:
        branches:
            -main
            jobs: 
                name:test
                runs-on: ubuntu-latest
                steps:
                    run: echo "Hello world"