name: Practice-ci-cd
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the code
        run: |
          echo "Testing the code"
          pwd
          ls -al
